version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--providers.docker"
      - "--providers.docker.swarmmode"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--api.insecure"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lehttpresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.lehttpresolver.acme.email=${ADMIN_EMAIL}"
      - "--certificatesresolvers.lehttpresolver.acme.storage=letsencrypt/acme.json"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "le_data:/letsencrypt"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    networks:
      - proxy

  agent:
    image: portainer/agent:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]

  portainer:
    image: portainer/portainer-ce:2.16.2
    command: --tlsskipverify -l devtainer=hidden --host tcp://tasks.agent:9001 --templates https://raw.githubusercontent.com/KyleFS/docker-dev-infrastructure/master/portainer-templates.json
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    networks:
      - agent_network

volumes:
  le_data:
  portainer_data:

networks:
  proxy:
    external: true
    driver: overlay
    attachable: true
  agent_network:
    driver: overlay
    attachable: true
