services:
  traefik:
    image: traefik:v2.11
    command:
      - "--providers.docker"
      - "--providers.docker.swarmmode"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--api.insecure"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lehttpresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.lehttpresolver.acme.email=${DEV_ADMIN_EMAIL}"
      - "--certificatesresolvers.lehttpresolver.acme.storage=letsencrypt/acme.json"
      - "--providers.file.filename=/etc/traefik/extra-hosts.yml"
      - "--providers.file.watch=true"
    ports:
      # The HTTP port
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "le_data:/letsencrypt"
      - "./extra-hosts.yml:/etc/traefik/extra-hosts.yml"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    networks:
      - proxy

  agent:
    image: portainer/agent:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/volumes:/var/lib/docker/volumes"
    networks:
      - devtainer_agent_network
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]

  portainer:
    image: portainer/portainer-ce:2.27.6
    command: --tlsskipverify -l devtainer=hidden --host tcp://tasks.agent:9001 --templates https://raw.githubusercontent.com/KyleFS/docker-dev-infrastructure/master/portainer-templates.json
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    networks:
      - devtainer_agent_network

volumes:
  le_data:
  portainer_data:
  authelia_data:

networks:
  proxy:
    external: true
    driver: overlay
    attachable: true
  devtainer_agent_network:
    external: true
    driver: overlay
    attachable: true
